// Code generated by wit-bindgen-go. DO NOT EDIT.

package module

import (
	"go.bytecodealliance.org/cm"
)

func lift_Version(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v Version) {
	v.Path = cm.LiftString[string](f0, f1)
	v.Version = cm.LiftString[string](f2, f3)
	return
}
